### ISSUE TITLE
Missing icons ...

### ISSUE THREAD

**Issue by baronleonardo** [OrancheloTeam/oranchelo-icon-theme#10] opened 2016-09-04 12:42 UTC
There are many gnome app icons are missing
like gnome-notes(bijiben), gnome-clock, gnome-boxes

There are other important icons too
like skype, vivaldi, franz, any icon for `spice` will be good, eagle and Kicad (PCB designers), nvidia settings, playonlinux, Qalculator, slack, smartgit, teamviewer, visual studio code, vmplayer

**Comment by SjorsVanGelderen** [comment] 2016-09-20 20:06
Not sure if it's related, but my GNOME Tweak Tool icon is missing since the last upgrade.

**Comment by Madh93** [comment] 2016-09-20 20:28
It seems that problem is related to #8. I will try Ubuntu Gnome to know the reason.

**Comment by Madh93** [comment] 2016-09-21 12:13
@SjorsVanGelderen I tried Ubuntu Gnome and `gnome-tweak-tool` icons is fine (see icon [here](https://github.com/OrancheloTeam/oranchelo-icon-theme/blob/master/Oranchelo/apps/scalable/gnome-tweak-tool.svg)).

Try uninstall and install again:

    sudo apt remove oranchelo-icon-theme
    sudo apt install oranchelo-icon-theme

**Comment by SjorsVanGelderen** [comment] 2016-09-21 20:33
@Madh93 It seems removing and reinstalling fixed the problem for me.
Cheers!

**Comment by zayronxio** [comment] 2018-02-21 06:19
the following icons have already been added:
*kicad
*smartgit
*slack
*bejiben
*skype
*vmplayer
*qalculator
*vivaldi
*gnome-boxes
*nvidia settings
*playonlinux
*gnome-notes
*franz

**Comment by zayronxio** [comment] 2018-02-28 02:51
all icons have been added

**Comment by zoxzinmin** [comment] 2018-04-08 19:30
Hi, I am using Ubuntu 16.04LTS version and also using Orenchelo icon theme with Arch theme. I am facing problem that Wireless icon and Battery icon missed in the windows menu bar after last update. Please solve the problem because of I love too much Orenchelo icon and do not want to use any other icon. Thank you.

Zox Zin Min

**Comment by yanike** [comment] 2018-04-18 19:32
Should this be closed?

**Comment by zayronxio** [comment] 2018-04-18 19:37
you're right

**Comment by zoxzinmin** [comment] 2018-04-20 17:51
![screenshot from 2018-04-21 00-15-27](https://user-images.githubusercontent.com/16510247/39066040-bcf96a16-44f9-11e8-9e83-91cf14c05e82.png)

The problem is still happening and not solve yet. Please fix this icon. Thank you for creating this awesome icon. Thank you.

**Comment by zoxzinmin** [comment] 2018-04-20 19:06
@zayronxio Please kindly fix this problem. Thank you.

**Comment by zayronxio** [comment] 2018-04-20 19:08
I work on it, I will soon have the solution

**Comment by zayronxio** [comment] 2018-04-23 13:15
check now please

**Comment by zoxzinmin** [comment] 2018-04-23 15:58
Now fixed the problem. Thanks a lot and a lot.

**Closed** 2018-04-23 16:01 UTC
Labels: enhancement

**Comment by vnpnlz** [comment] 2018-07-10 07:35
bumping on this thread. I can't find the slack icon :(
